---
- name: Installing php apt repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Installing php7.1
  apt:
    name: php7.1 

- name: Installing php dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - php7.1-xsl
    - php7.1-intl
    - php7.1-gd
    - php7.1-mbstring
    - php7.1-xml
    - php7.1-curl
    - php7.1-mysql
    - php7.1-zip
    - php7.1-soap
    - php7.1-bcmath
