- hosts: localhost
  gather_facts: no
  connection: local
  roles:
     - folders
     - folder_permissions
     - pfsense_deploy_provision
     - template_deployment

- hosts: AD
  gather_facts: no
  strategy: free
  roles:
    - windows_server_provision_AD

- hosts: Linux-A, Linux-B, Linux-C, WEB, DB, GIT
  strategy: free
  gather_facts: no
  tasks:
    - name: Wait For AD connection
      wait_for_connection:
        timeout: 30000
        sleep: 5

- hosts: Linux-A, Linux-B, Linux-C, WEB, DB, GIT
  strategy: free
  roles:
    - local_users_Linux

- hosts: Windows-A, Windows-B, FTP
  strategy: free
  gather_facts: no
  roles:
    - Windows_Client_Provision

- hosts: GIT, WEB, DB
  strategy: free
  become: yes
  roles:
    - disable_firewall

- hosts: GIT
  gather_facts: no
  strategy: free
  become: yes
  roles:
    - gitlab


- hosts: DB
  gather_facts: no
  strategy: free
  become: true
  roles:
    - ansible-role-mysql-master


- hosts: WEB
  become: true
  strategy: free
  roles:
    - install_php
    - ansible-role-apache-master
    - ansible-role-composer-master
    - install_magento

- hosts: WEB, DB
  become: true
  strategy: free
  roles:
    - ansible-docker-master