    - name:  Clone a virtual machine from Linux template and customize the addresses
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        state: present
        folder:  'Lab/PaloAltoLab/{{ idx + 1 }}: PA - {{ item }}'
        template: "{{ template }}"
        name: "{{ vm_name }}-{{ item }}"
        cluster: "{{ cluster }}"
        networks:
          - name: "{{ vmnet }}"
            ip: "{{ ip | ipmath(idx) }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway | ipmath(idx) }}"
            dns_servers: "{{ dns_list }}"
        wait_for_ip_address: True
        customization:
          dns_servers: "{{ dns_list }}"
      delegate_to: localhost
      async: 600
      poll: 0