    - name:  Clone a virtual machine from Linux template and customize the addresses
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        state: present
        folder:  'Lab/PaloAltoLab/{{ idx + 1 }}: PA - {{ item }}'
        template: "{{ template }}"
        name: "{{ vm_name }}-{{ item }}"
        cluster: "{{ cluster }}"
        networks:
          - name: "{{ vmnet }}"
            ip: "{{ ip | ipmath(idx) }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway | ipmath(idx) }}"
            dns_servers: "{{ dns_list }}"
        customization:
          dns_servers: "{{ dns_list }}"
      delegate_to: localhost
      register: deployment_linux
      async: 3000
      poll: 0
      loop: "{{ ubit }}"
      loop_control:
        index_var: idx

    - name: Check sync status
      async_status:
        jid: "{{ deployment_linux_item.ansible_job_id }}"
      loop: "{{ deployment_linux.results }}"
      loop_control:
        loop_var: "deployment_linux_item"
      register: async_poll_results
      until: async_poll_results.finished
      retries: 30000
